// <auto-generated />
using System;
using APEC.ProyectoFinal.API.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APEC.ProyectoFinal.API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APEC.ProyectoFinal.API.Entities.CuentaContable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Balance")
                        .HasColumnType("real");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CuentaMayor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<bool>("PermiteTransaciones")
                        .HasColumnType("bit");

                    b.Property<int>("TipoCuentaContableId")
                        .HasColumnType("int");

                    b.Property<int>("TipoMonedaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoCuentaContableId");

                    b.HasIndex("TipoMonedaId");

                    b.ToTable("CuentaContables");
                });

            modelBuilder.Entity("APEC.ProyectoFinal.API.Entities.EntradaContable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CuentaContableId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAsiento")
                        .HasColumnType("datetime2");

                    b.Property<double>("MontoAsiento")
                        .HasColumnType("float");

                    b.Property<int>("SistemaAuxiliaresId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CuentaContableId");

                    b.HasIndex("SistemaAuxiliaresId");

                    b.ToTable("EntradaContables");
                });

            modelBuilder.Entity("APEC.ProyectoFinal.API.Entities.SistemaAuxiliares", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SistemaAuxiliares");
                });

            modelBuilder.Entity("APEC.ProyectoFinal.API.Entities.TipoCuentaContable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoCuentaContables");
                });

            modelBuilder.Entity("APEC.ProyectoFinal.API.Entities.TipoMoneda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<double>("UltimaTasaCambiara")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("TipoMonedas");
                });

            modelBuilder.Entity("APEC.ProyectoFinal.API.Entities.CuentaContable", b =>
                {
                    b.HasOne("APEC.ProyectoFinal.API.Entities.TipoCuentaContable", "TipoCuentaContable")
                        .WithMany()
                        .HasForeignKey("TipoCuentaContableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APEC.ProyectoFinal.API.Entities.TipoMoneda", "TipoMoneda")
                        .WithMany()
                        .HasForeignKey("TipoMonedaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoCuentaContable");

                    b.Navigation("TipoMoneda");
                });

            modelBuilder.Entity("APEC.ProyectoFinal.API.Entities.EntradaContable", b =>
                {
                    b.HasOne("APEC.ProyectoFinal.API.Entities.CuentaContable", "CuentaContable")
                        .WithMany()
                        .HasForeignKey("CuentaContableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APEC.ProyectoFinal.API.Entities.SistemaAuxiliares", "SistemaAuxiliares")
                        .WithMany()
                        .HasForeignKey("SistemaAuxiliaresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuentaContable");

                    b.Navigation("SistemaAuxiliares");
                });
#pragma warning restore 612, 618
        }
    }
}
